## Which jobs grew in pay after adjusting for inflation.

In [1]:
import sqlite3
import os
import pandas as pd

In [2]:
occupation_file_name = os.path.join('Occupation_Data.csv')

In [3]:
occupation = pd.read_csv(occupation_file_name, index_col=None)

In [4]:
occupation.head()

,OCC_CODE,OCC_TITLE,OCC_GROUP,TOT_EMP,EMP_PRSE,H_MEAN,A_MEAN,MEAN_PRSE,H_PCT10,H_PCT25,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,YEAR
0,00-0000,All Occupations,total,652100.0,1.3,21.99,45740.0,1.5,9.18,11.90,17.47,26.74,38.71,19100.0,24760.0,36350.0,55610.0,80510.0,2018
1,11-0000,Management Occupations,major,31180.0,2.6,49.67,103320.0,1.5,19.90,28.60,42.37,61.46,87.13,41400.0,59490.0,88120.0,127850.0,181230.0,2018
2,11-1011,Chief Executives,detailed,1210.0,6.1,73.53,152940.0,2.8,28.36,41.72,61.92,95.40,NaN,58980.0,86770.0,128800.0,198420.0,NaN,2018
3,11-1021,General and Operations Managers,detailed,10360.0,4.4,48.99,101900.0,2.1,17.27,24.89,38.13,61.21,96.22,35920.0,51770.0,79310.0,127320.0,200130.0,2018
4,11-2011,Advertising and Promotions Managers,detailed,60.0,16.8,53.04,110320.0,10.4,18.64,26.74,44.61,78.86,98.10,38770.0,55630.0,92780.0,164030.0,204050.0,2018

In economics the term real dollars is the value of currency after being adjusted for inflation. I will turn everything into 2018 dollars and to compute the difference I used an inflation calculator which can be found in the following website 
https://www.usinflationcalculator.com/

Adjusted for inflation, 1.00 in 2003 is equal to 1.36 in 2018, with a 36.5% cumulative rate of inflation.

Adjusted for inflation, 1.00 in 2008 is equal to 1.17 in 2018, with a 16.6% cumulative rate of inflation.

Adjusted for inflation, 1.00 in 2013 is equal to 1.08 in 2018, with a 7.8% cumulative rate of inflation.

The following sections will need to be adjusted based on their year. 
H_PCT10, H_PCT25, H_MEDIAN, H_CT75, H_PCT90, A_PCT10, A_PCT25, A_MEDIAN, A_PCT75, A_PCT90

In [5]:
year2018 = occupation['YEAR'] == 2018
year2013 = occupation['YEAR'] == 2013
year2008 = occupation['YEAR'] == 2008
year2003 = occupation['YEAR'] == 2003

## Converting to 2018 dollars

In [6]:
occupation.columns[5:18]

for x in occupation.columns[5:18]:
    occupation.loc[(occupation.YEAR == 2013), x] *=1.08
    occupation.loc[(occupation.YEAR == 2008), x] *=1.17
    occupation.loc[(occupation.YEAR == 2003), x] *=1.36

## Checking to see how many occupations existed across all four sample years

In [7]:
occ_count=occupation.groupby('OCC_CODE')
occ_count_all = occ_count.size()
occ_count_all.value_counts()

4    384
2    139
3    128
1     80
5      5
dtype: int64

## Found an error in the data I need to find out where it is and remove it. (Skip to next section if you wish to skip this)
It is odd that there is a 5 in the options I need to figure out which year(s) have duplicate occupations.

In [8]:
dupe_year=occupation.groupby(['OCC_CODE', 'YEAR']).size() > 1
print(dupe_year.value_counts())
dupe_year_list=dupe_year[dupe_year == True]
dupe_year_list

False    2293
True        5
dtype: int64

OCC_CODE  YEAR
53-7061   2003    True
53-7062   2003    True
53-7063   2003    True
53-7064   2003    True
53-7081   2003    True
dtype: bool

2003 Seems to have produced all of the duplicates and here is the list of duplicate job codes 

I am going to have to remove the duplicate data from the dataset

In [9]:
dupes_year = occupation[occupation.duplicated(('OCC_CODE', 'YEAR'), keep=False)]

In [10]:
dupes_year.sort_values('OCC_CODE')

,OCC_CODE,OCC_TITLE,OCC_GROUP,TOT_EMP,EMP_PRSE,H_MEAN,A_MEAN,MEAN_PRSE,H_PCT10,H_PCT25,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,YEAR
2292,53-7061,Cleaners of vehicles and equipment,NaN,1260.0,15.7,13.1784,27404.0,6.664,8.1192,9.3432,11.5736,15.3408,19.6656,16891.2,19434.4,24085.6,31905.6,40908.8,2003
2298,53-7061,Cleaners of vehicles and equipment,NaN,1320.0,12.4,13.9264,28954.4,10.336,8.0784,9.2344,11.5464,16.1160,24.1672,16796.0,19203.2,24017.6,33524.0,50252.0,2003
2293,53-7062,"Laborers and freight, stock, and material move...",NaN,12700.0,5.6,15.3000,31824.0,6.120,9.5608,11.2200,13.4912,16.4016,26.5336,19883.2,23337.6,28070.4,34122.4,55188.8,2003
2299,53-7062,"Laborers and freight, stock, and material move...",NaN,12600.0,9.3,15.6672,32572.0,5.304,9.5336,11.4512,14.0080,17.9520,26.1800,19842.4,23813.6,29131.2,37345.6,54454.4,2003
2294,53-7063,Machine feeders and offbearers,NaN,1650.0,29.6,17.0952,35550.4,5.848,11.0432,13.0016,14.9736,20.4136,24.3304,22956.8,27036.8,31130.4,42445.6,50605.6,2003
2300,53-7063,Machine feeders and offbearers,NaN,1410.0,29.9,17.0680,35509.6,6.936,10.7848,12.6888,14.8512,20.4272,24.2624,22426.4,26397.6,30885.6,42486.4,50456.0,2003
2295,53-7064,"Packers and packagers, hand",NaN,4970.0,11.3,11.9952,24956.0,2.312,8.2008,9.4248,11.3832,13.9264,17.5168,17054.4,19611.2,23691.2,28968.0,36420.8,2003
2301,53-7064,"Packers and packagers, hand",NaN,4650.0,9.0,12.1448,25255.2,3.128,8.2280,9.3432,11.3016,14.1984,18.2784,17095.2,19434.4,23514.4,29525.6,38025.6,2003
2296,53-7081,Refuse and recyclable material collectors,NaN,400.0,29.9,16.1976,33687.2,6.936,10.4992,12.8520,15.9120,18.8088,22.6032,21855.2,26724.0,33088.8,39127.2,47001.6,2003
2302,53-7081,Refuse and recyclable material collectors,NaN,420.0,29.0,15.7488,32748.8,8.024,10.7032,12.2672,14.5384,18.4824,22.1816,22249.6,25513.6,30232.8,38460.8,46131.2,2003

Much to my suprise the data is different. I suppose data gathering methods were not refined in 2003. To correct this I will merge the data and take the average. Once I get the averages I will add this to a new data base and remove all other duplicates.

In [11]:
#Had to change the as_index to False so it would create number indexs rather than use the OOC_code
combine = dupes_year.groupby(['OCC_CODE', 'OCC_TITLE', 'YEAR'], as_index=False).mean()
combine = combine.copy()

In [12]:
combine['OCC_GROUP']=pd.np.NaN

In [13]:
new_occupation= occupation.append(combine, ignore_index=True, sort=False)

In [14]:
new_occupation.drop_duplicates(('OCC_CODE', 'YEAR'), keep='last', inplace=True)

In [15]:
occ_count=new_occupation.groupby('OCC_CODE')
occ_count_all = occ_count.size()
occ_count_4=occ_count.size() == 4
occ_count_3=occ_count.size() == 3
occ_count_2=occ_count.size() == 2
occ_count_1=occ_count.size() == 1

In [16]:
print(occ_count_all.value_counts())

4    389
2    139
3    128
1     80
dtype: int64

The problem has been solved. I know this becasue the 5 group no longer exists and the 4 group increased in size by five (the same number as the old 5 group). 
There are 736 unique occupations on this list of those occupations 389 occupations existed all four observed years, 128 existed for three observed years, 139 exitsed for two observed years, and 80 existed for only one observed year.

In [17]:
total_instance=new_occupation.groupby(['OCC_CODE'])
total_instance=total_instance.size()
dict4={}
dict3={}
dict2={}
dict1={}
for y, x in total_instance.items():
    if x == 4:
        dict4.update({y:x})
    elif x == 3:
        dict3.update({y:x})
    elif x == 2:
        dict2.update({y:x})
    else:
        dict1.update({y:x})

In [18]:
dict4

{'00-0000': 4,
 '11-0000': 4,
 '11-1011': 4,
 '11-1021': 4,
 '11-2011': 4,
 '11-2021': 4,
 '11-2022': 4,
 '11-2031': 4,
 '11-3011': 4,
 '11-3021': 4,
 '11-3051': 4,
 '11-3061': 4,
 '11-3071': 4,
 '11-9021': 4,
 '11-9031': 4,
 '11-9032': 4,
 '11-9041': 4,
 '11-9051': 4,
 '11-9061': 4,
 '11-9081': 4,
 '11-9111': 4,
 '11-9121': 4,
 '11-9131': 4,
 '11-9141': 4,
 '11-9151': 4,
 '13-0000': 4,
 '13-1031': 4,
 '13-1041': 4,
 '13-1051': 4,
 '13-1071': 4,
 '13-1111': 4,
 '13-1121': 4,
 '13-2011': 4,
 '13-2021': 4,
 '13-2031': 4,
 '13-2041': 4,
 '13-2051': 4,
 '13-2052': 4,
 '13-2053': 4,
 '13-2061': 4,
 '13-2071': 4,
 '13-2072': 4,
 '13-2081': 4,
 '13-2082': 4,
 '15-0000': 4,
 '15-2031': 4,
 '15-2041': 4,
 '17-0000': 4,
 '17-1011': 4,
 '17-1012': 4,
 '17-1021': 4,
 '17-1022': 4,
 '17-2041': 4,
 '17-2051': 4,
 '17-2061': 4,
 '17-2071': 4,
 '17-2072': 4,
 '17-2081': 4,
 '17-2111': 4,
 '17-2141': 4,
 '17-3011': 4,
 '17-3012': 4,
 '17-3013': 4,
 '17-3023': 4,
 '17-3025': 4,
 '17-3026': 4,
 '17-3027': 4,
 '17-3031': 4,
 '19-0000': 4,
 '19-2031': 4,
 '19-2041': 4,
 '19-3031': 4,
 '19-4031': 4,
 '19-4091': 4,
 '21-0000': 4,
 '21-1012': 4,
 '21-1015': 4,
 '21-1022': 4,
 '21-1023': 4,
 '21-1091': 4,
 '21-1093': 4,
 '21-2011': 4,
 '23-0000': 4,
 '23-1011': 4,
 '23-2011': 4,
 '23-2093': 4,
 '25-0000': 4,
 '25-1011': 4,
 '25-1022': 4,
 '25-1072': 4,
 '25-1121': 4,
 '25-1123': 4,
 '25-1194': 4,
 '25-2011': 4,
 '25-2021': 4,
 '25-2022': 4,
 '25-2031': 4,
 '25-3021': 4,
 '25-4021': 4,
 '25-4031': 4,
 '25-9031': 4,
 '27-0000': 4,
 '27-1011': 4,
 '27-1021': 4,
 '27-1023': 4,
 '27-1024': 4,
 '27-1025': 4,
 '27-1026': 4,
 '27-2011': 4,
 '27-2012': 4,
 '27-2022': 4,
 '27-3031': 4,
 '27-3041': 4,
 '27-3042': 4,
 '27-3043': 4,
 '27-4011': 4,
 '27-4012': 4,
 '27-4021': 4,
 '27-4032': 4,
 '29-0000': 4,
 '29-1011': 4,
 '29-1031': 4,
 '29-1041': 4,
 '29-1051': 4,
 '29-1062': 4,
 '29-1063': 4,
 '29-1065': 4,
 '29-1066': 4,
 '29-1067': 4,
 '29-1071': 4,
 '29-1122': 4,
 '29-1123': 4,
 '29-1125': 4,
 '29-1126': 4,
 '29-1127': 4,
 '29-1131': 4,
 '29-2021': 4,
 '29-2031': 4,
 '29-2032': 4,
 '29-2033': 4,
 '29-2034': 4,
 '29-2041': 4,
 '29-2052': 4,
 '29-2055': 4,
 '29-2056': 4,
 '29-2061': 4,
 '29-2071': 4,
 '29-2081': 4,
 '29-9091': 4,
 '31-0000': 4,
 '31-1011': 4,
 '31-2011': 4,
 '31-2021': 4,
 '31-2022': 4,
 '31-9011': 4,
 '31-9091': 4,
 '31-9092': 4,
 '31-9093': 4,
 '31-9094': 4,
 '31-9096': 4,
 '33-0000': 4,
 '33-1012': 4,
 '33-2011': 4,
 '33-3021': 4,
 '33-3051': 4,
 '33-9021': 4,
 '33-9032': 4,
 '35-0000': 4,
 '35-1011': 4,
 '35-1012': 4,
 '35-2011': 4,
 '35-2012': 4,
 '35-2014': 4,
 '35-2015': 4,
 '35-2021': 4,
 '35-3011': 4,
 '35-3021': 4,
 '35-3022': 4,
 '35-3031': 4,
 '35-3041': 4,
 '35-9011': 4,
 '35-9021': 4,
 '35-9031': 4,
 '37-0000': 4,
 '37-1011': 4,
 '37-1012': 4,
 '37-2011': 4,
 '37-2012': 4,
 '37-2021': 4,
 '37-3011': 4,
 '39-0000': 4,
 '39-1021': 4,
 '39-2011': 4,
 '39-2021': 4,
 '39-3031': 4,
 '39-3091': 4,
 '39-5012': 4,
 '39-6011': 4,
 '39-9011': 4,
 '39-9021': 4,
 '39-9031': 4,
 '39-9032': 4,
 '39-9041': 4,
 '41-0000': 4,
 '41-1011': 4,
 '41-1012': 4,
 '41-2011': 4,
 '41-2021': 4,
 '41-2022': 4,
 '41-2031': 4,
 '41-3011': 4,
 '41-3021': 4,
 '41-3031': 4,
 '41-3041': 4,
 '41-4011': 4,
 '41-4012': 4,
 '41-9011': 4,
 '41-9022': 4,
 '41-9031': 4,
 '41-9041': 4,
 '43-0000': 4,
 '43-1011': 4,
 '43-2011': 4,
 '43-3011': 4,
 '43-3021': 4,
 '43-3031': 4,
 '43-3051': 4,
 '43-3061': 4,
 '43-3071': 4,
 '43-4041': 4,
 '43-4051': 4,
 '43-4061': 4,
 '43-4071': 4,
 '43-4081': 4,
 '43-4111': 4,
 '43-4121': 4,
 '43-4131': 4,
 '43-4141': 4,
 '43-4161': 4,
 '43-4171': 4,
 '43-4181': 4,
 '43-5011': 4,
 '43-5021': 4,
 '43-5031': 4,
 '43-5032': 4,
 '43-5041': 4,
 '43-5051': 4,
 '43-5052': 4,
 '43-5053': 4,
 '43-5061': 4,
 '43-5071': 4,
 '43-5081': 4,
 '43-5111': 4,
 '43-6011': 4,
 '43-6012': 4,
 '43-6013': 4,
 '43-6014': 4,
 '43-9011': 4,
 '43-9021': 4,
 '43-9022': 4,
 '43-9041': 4,
 '43-9051': 4,
 '43-9061': 4,
 '43-9071': 4,
 '43-9111': 4,
 '45-0000': 4,
 '45-2092': 4,
 '45-2093': 4,
 '47-0000': 4,
 '47-1011': 4,
 '47-2021': 4,
 '47-2031': 4,
 '47-2041': 4,
 '47-2044': 4,
 '47-2051': 4,
 '47-2061': 4,
 '47-2071': 4,
 '47-2073': 4,
 '47-2081': 4,
 '47-2111': 4,
 '47-2121': 4,
 '47-2141': 4,
 '47-2151': 4,
 '47-2152': 4,
 '47-2181': 4,
 '47-2211': 4,
 '47-2221': 4,
 '47-3011': 4,
 '47-3012': 4,
 '47-3013': 4,
 '47-3015': 4,
 '47-3016': 4,
 '47-4011': 4,
 '47-4041': 4,
 '47-4051': 4,
 '47-4071': 4,
 '49-0000': 4,
 '49-1011': 4,
 '49-2011': 4,
 '49-2022': 4,
 '49-2094': 4,
 '49-2097': 4,
 '49-2098': 4,
 '49-3011': 4,
 '49-3021': 4,
 '49-3022': 4,
 '49-3023': 4,
 '49-3031': 4,
 '49-3041': 4,
 '49-3042': 4,
 '49-3052': 4,
 '49-3053': 4,
 '49-3093': 4,
 '49-9012': 4,
 '49-9021': 4,
 '49-9041': 4,
 '49-9043': 4,
 '49-9044': 4,
 '49-9051': 4,
 '49-9052': 4,
 '49-9062': 4,
 '49-9091': 4,
 '49-9094': 4,
 '49-9098': 4,
 '51-0000': 4,
 '51-1011': 4,
 '51-2041': 4,
 '51-3011': 4,
 '51-3021': 4,
 '51-3091': 4,
 '51-3092': 4,
 '51-4011': 4,
 '51-4021': 4,
 '51-4023': 4,
 '51-4031': 4,
 '51-4033': 4,
 '51-4041': 4,
 '51-4072': 4,
 '51-4081': 4,
 '51-4111': 4,
 '51-4121': 4,
 '51-4122': 4,
 '51-4193': 4,
 '51-6011': 4,
 '51-6021': 4,
 '51-6031': 4,
 '51-6052': 4,
 '51-6093': 4,
 '51-7011': 4,
 '51-7021': 4,
 '51-7041': 4,
 '51-7042': 4,
 '51-8031': 4,
 '51-8091': 4,
 '51-9011': 4,
 '51-9012': 4,
 '51-9021': 4,
 '51-9022': 4,
 '51-9023': 4,
 '51-9032': 4,
 '51-9041': 4,
 '51-9061': 4,
 '51-9081': 4,
 '51-9083': 4,
 '51-9111': 4,
 '51-9121': 4,
 '51-9123': 4,
 '51-9191': 4,
 '51-9195': 4,
 '51-9196': 4,
 '51-9198': 4,
 '53-0000': 4,
 '53-2012': 4,
 '53-3021': 4,
 '53-3022': 4,
 '53-3031': 4,
 '53-3032': 4,
 '53-3033': 4,
 '53-3041': 4,
 '53-6031': 4,
 '53-6051': 4,
 '53-7021': 4,
 '53-7032': 4,
 '53-7051': 4,
 '53-7061': 4,
 '53-7062': 4,
 '53-7063': 4,
 '53-7064': 4,
 '53-7081': 4}

In [19]:
check=(new_occupation.groupby(['OCC_CODE','YEAR'])).size()

In [20]:
occ_yeardict={}
for y,x in check.items():
    (a,b)=y
    if a in occ_yeardict:
        t=occ_yeardict[a]
        t = t + (b,)
        occ_yeardict.update({a:t})
    else:
        occ_yeardict.update({a:(b,)})

In [21]:
occ_yeardict

{'00-0000': (2003, 2008, 2013, 2018),
 '11-0000': (2003, 2008, 2013, 2018),
 '11-1011': (2003, 2008, 2013, 2018),
 '11-1021': (2003, 2008, 2013, 2018),
 '11-1031': (2003, 2008, 2013),
 '11-2011': (2003, 2008, 2013, 2018),
 '11-2021': (2003, 2008, 2013, 2018),
 '11-2022': (2003, 2008, 2013, 2018),
 '11-2031': (2003, 2008, 2013, 2018),
 '11-3011': (2003, 2008, 2013, 2018),
 '11-3021': (2003, 2008, 2013, 2018),
 '11-3031': (2008, 2013, 2018),
 '11-3040': (2003,),
 '11-3041': (2008,),
 '11-3042': (2008,),
 '11-3049': (2008,),
 '11-3051': (2003, 2008, 2013, 2018),
 '11-3061': (2003, 2008, 2013, 2018),
 '11-3071': (2003, 2008, 2013, 2018),
 '11-3111': (2013, 2018),
 '11-3121': (2013, 2018),
 '11-3131': (2013, 2018),
 '11-9021': (2003, 2008, 2013, 2018),
 '11-9031': (2003, 2008, 2013, 2018),
 '11-9032': (2003, 2008, 2013, 2018),
 '11-9033': (2008, 2013, 2018),
 '11-9039': (2008, 2013, 2018),
 '11-9041': (2003, 2008, 2013, 2018),
 '11-9051': (2003, 2008, 2013, 2018),
 '11-9061': (2003, 2008, 2013, 2018),
 '11-9081': (2003, 2008, 2013, 2018),
 '11-9111': (2003, 2008, 2013, 2018),
 '11-9121': (2003, 2008, 2013, 2018),
 '11-9131': (2003, 2008, 2013, 2018),
 '11-9141': (2003, 2008, 2013, 2018),
 '11-9151': (2003, 2008, 2013, 2018),
 '11-9161': (2013,),
 '11-9199': (2008, 2013, 2018),
 '13-0000': (2003, 2008, 2013, 2018),
 '13-1011': (2003, 2018),
 '13-1020': (2018,),
 '13-1021': (2003, 2008, 2013),
 '13-1022': (2003, 2008, 2013),
 '13-1023': (2003, 2008, 2013),
 '13-1031': (2003, 2008, 2013, 2018),
 '13-1032': (2003, 2008, 2013),
 '13-1041': (2003, 2008, 2013, 2018),
 '13-1051': (2003, 2008, 2013, 2018),
 '13-1061': (2008,),
 '13-1071': (2003, 2008, 2013, 2018),
 '13-1072': (2003, 2008),
 '13-1073': (2003, 2008),
 '13-1075': (2013, 2018),
 '13-1079': (2008,),
 '13-1081': (2008, 2013, 2018),
 '13-1111': (2003, 2008, 2013, 2018),
 '13-1121': (2003, 2008, 2013, 2018),
 '13-1131': (2013, 2018),
 '13-1141': (2013, 2018),
 '13-1151': (2013, 2018),
 '13-1161': (2013, 2018),
 '13-1199': (2008, 2013, 2018),
 '13-2011': (2003, 2008, 2013, 2018),
 '13-2021': (2003, 2008, 2013, 2018),
 '13-2031': (2003, 2008, 2013, 2018),
 '13-2041': (2003, 2008, 2013, 2018),
 '13-2051': (2003, 2008, 2013, 2018),
 '13-2052': (2003, 2008, 2013, 2018),
 '13-2053': (2003, 2008, 2013, 2018),
 '13-2061': (2003, 2008, 2013, 2018),
 '13-2071': (2003, 2008, 2013, 2018),
 '13-2072': (2003, 2008, 2013, 2018),
 '13-2081': (2003, 2008, 2013, 2018),
 '13-2082': (2003, 2008, 2013, 2018),
 '13-2099': (2008, 2013, 2018),
 '15-0000': (2003, 2008, 2013, 2018),
 '15-1021': (2003, 2008),
 '15-1031': (2003, 2008),
 '15-1032': (2003, 2008),
 '15-1041': (2003, 2008),
 '15-1051': (2003, 2008),
 '15-1061': (2003, 2008),
 '15-1071': (2003, 2008),
 '15-1081': (2003, 2008),
 '15-1099': (2008,),
 '15-1121': (2013, 2018),
 '15-1122': (2013, 2018),
 '15-1131': (2013, 2018),
 '15-1132': (2013, 2018),
 '15-1133': (2013, 2018),
 '15-1134': (2013, 2018),
 '15-1141': (2013, 2018),
 '15-1142': (2013, 2018),
 '15-1143': (2013, 2018),
 '15-1151': (2013, 2018),
 '15-1152': (2013, 2018),
 '15-1199': (2013, 2018),
 '15-2011': (2008, 2013),
 '15-2031': (2003, 2008, 2013, 2018),
 '15-2041': (2003, 2008, 2013, 2018),
 '17-0000': (2003, 2008, 2013, 2018),
 '17-1011': (2003, 2008, 2013, 2018),
 '17-1012': (2003, 2008, 2013, 2018),
 '17-1021': (2003, 2008, 2013, 2018),
 '17-1022': (2003, 2008, 2013, 2018),
 '17-2011': (2018,),
 '17-2021': (2018,),
 '17-2031': (2013,),
 '17-2041': (2003, 2008, 2013, 2018),
 '17-2051': (2003, 2008, 2013, 2018),
 '17-2061': (2003, 2008, 2013, 2018),
 '17-2071': (2003, 2008, 2013, 2018),
 '17-2072': (2003, 2008, 2013, 2018),
 '17-2081': (2003, 2008, 2013, 2018),
 '17-2111': (2003, 2008, 2013, 2018),
 '17-2112': (2008, 2013, 2018),
 '17-2131': (2008, 2013, 2018),
 '17-2141': (2003, 2008, 2013, 2018),
 '17-2199': (2008, 2013, 2018),
 '17-3011': (2003, 2008, 2013, 2018),
 '17-3012': (2003, 2008, 2013, 2018),
 '17-3013': (2003, 2008, 2013, 2018),
 '17-3019': (2008, 2013, 2018),
 '17-3022': (2008, 2013, 2018),
 '17-3023': (2003, 2008, 2013, 2018),
 '17-3024': (2003, 2008),
 '17-3025': (2003, 2008, 2013, 2018),
 '17-3026': (2003, 2008, 2013, 2018),
 '17-3027': (2003, 2008, 2013, 2018),
 '17-3029': (2008, 2013, 2018),
 '17-3031': (2003, 2008, 2013, 2018),
 '19-0000': (2003, 2008, 2013, 2018),
 '19-1012': (2008, 2018),
 '19-1013': (2008,),
 '19-1022': (2013,),
 '19-1023': (2013, 2018),
 '19-1029': (2008, 2018),
 '19-1031': (2008, 2013, 2018),
 '19-1042': (2013, 2018),
 '19-2021': (2008, 2018),
 '19-2031': (2003, 2008, 2013, 2018),
 '19-2041': (2003, 2008, 2013, 2018),
 '19-2042': (2003, 2013, 2018),
 '19-2099': (2013, 2018),
 '19-3011': (2008,),
 '19-3021': (2003, 2008),
 '19-3022': (2018,),
 '19-3031': (2003, 2008, 2013, 2018),
 '19-3039': (2013, 2018),
 '19-3051': (2008, 2013, 2018),
 '19-3099': (2008, 2013, 2018),
 '19-4011': (2018,),
 '19-4021': (2013, 2018),
 '19-4031': (2003, 2008, 2013, 2018),
 '19-4061': (2008, 2013, 2018),
 '19-4091': (2003, 2008, 2013, 2018),
 '19-4092': (2008,),
 '19-4099': (2008, 2013, 2018),
 '21-0000': (2003, 2008, 2013, 2018),
 '21-1011': (2003, 2008, 2013),
 '21-1012': (2003, 2008, 2013, 2018),
 '21-1013': (2008, 2013, 2018),
 '21-1014': (2003, 2008, 2013),
 '21-1015': (2003, 2008, 2013, 2018),
 '21-1018': (2018,),
 '21-1019': (2013,),
 '21-1021': (2008, 2013, 2018),
 '21-1022': (2003, 2008, 2013, 2018),
 '21-1023': (2003, 2008, 2013, 2018),
 '21-1029': (2008, 2018),
 '21-1091': (2003, 2008, 2013, 2018),
 '21-1092': (2008, 2013, 2018),
 '21-1093': (2003, 2008, 2013, 2018),
 '21-1094': (2013, 2018),
 '21-1099': (2008, 2013, 2018),
 '21-2011': (2003, 2008, 2013, 2018),
 '23-0000': (2003, 2008, 2013, 2018),
 '23-1011': (2003, 2008, 2013, 2018),
 '23-1012': (2018,),
 '23-1021': (2013,),
 '23-1022': (2018,),
 '23-1023': (2003, 2013, 2018),
 '23-2011': (2003, 2008, 2013, 2018),
 '23-2091': (2008, 2013, 2018),
 '23-2092': (2003, 2008),
 '23-2093': (2003, 2008, 2013, 2018),
 '23-2099': (2008, 2013, 2018),
 '25-0000': (2003, 2008, 2013, 2018),
 '25-1011': (2003, 2008, 2013, 2018),
 '25-1021': (2003, 2008, 2013),
 '25-1022': (2003, 2008, 2013, 2018),
 '25-1042': (2008, 2013),
 '25-1052': (2003, 2008, 2013),
 '25-1054': (2003, 2013),
 '25-1063': (2008, 2013),
 '25-1065': (2013,),
 '25-1066': (2003, 2008, 2013),
 '25-1067': (2013, 2018),
 '25-1071': (2008, 2013),
 '25-1072': (2003, 2008, 2013, 2018),
 '25-1081': (2008, 2013, 2018),
 '25-1111': (2008, 2013),
 '25-1113': (2013,),
 '25-1121': (2003, 2008, 2013, 2018),
 '25-1122': (2003, 2008, 2013),
 '25-1123': (2003, 2008, 2013, 2018),
 '25-1124': (2008, 2013),
 '25-1125': (2008, 2013),
 '25-1126': (2003, 2008, 2013),
 '25-1193': (2013,),
 '25-1194': (2003, 2008, 2013, 2018),
 '25-1199': (2008, 2013, 2018),
 '25-2011': (2003, 2008, 2013, 2018),
 '25-2012': (2008, 2013, 2018),
 '25-2021': (2003, 2008, 2013, 2018),
 '25-2022': (2003, 2008, 2013, 2018),
 '25-2031': (2003, 2008, 2013, 2018),
 '25-2032': (2008, 2018),
 '25-2041': (2003, 2008),
 '25-2042': (2008,),
 '25-2043': (2008,),
 '25-2052': (2013, 2018),
 '25-2053': (2013, 2018),
 '25-2054': (2013, 2018),
 '25-2059': (2013, 2018),
 '25-3011': (2008, 2013, 2018),
 '25-3021': (2003, 2008, 2013, 2018),
 '25-3097': (2018,),
 '25-3098': (2013, 2018),
 '25-3099': (2008, 2013),
 '25-4010': (2003,),
 '25-4012': (2008, 2013, 2018),
 '25-4021': (2003, 2008, 2013, 2018),
 '25-4031': (2003, 2008, 2013, 2018),
 '25-9021': (2008, 2018),
 '25-9031': (2003, 2008, 2013, 2018),
 '25-9041': (2008, 2013, 2018),
 '25-9099': (2013, 2018),
 '27-0000': (2003, 2008, 2013, 2018),
 '27-1011': (2003, 2008, 2013, 2018),
 '27-1013': (2008, 2018),
 '27-1014': (2003, 2018),
 '27-1021': (2003, 2008, 2013, 2018),
 '27-1023': (2003, 2008, 2013, 2018),
 '27-1024': (2003, 2008, 2013, 2018),
 '27-1025': (2003, 2008, 2013, 2018),
 '27-1026': (2003, 2008, 2013, 2018),
 '27-1027': (2003, 2013, 2018),
 '27-1029': (2018,),
 '27-2011': (2003, 2008, 2013, 2018),
 '27-2012': (2003, 2008, 2013, 2018),
 '27-2021': (2003, 2008, 2018),
 '27-2022': (2003, 2008, 2013, 2018),
 '27-2032': (2003, 2008),
 '27-2041': (2013,),
 '27-2042': (2008, 2013, 2018),
 '27-2099': (2008, 2013, 2018),
 '27-3010': (2003,),
 '27-3011': (2008, 2013, 2018),
 '27-3012': (2008, 2013),
 '27-3020': (2003,),
 '27-3022': (2008, 2013, 2018),
 '27-3031': (2003, 2008, 2013, 2018),
 '27-3041': (2003, 2008, 2013, 2018),
 '27-3042': (2003, 2008, 2013, 2018),
 '27-3043': (2003, 2008, 2013, 2018),
 '27-3091': (2008, 2013, 2018),
 '27-3099': (2008, 2013, 2018),
 '27-4011': (2003, 2008, 2013, 2018),
 '27-4012': (2003, 2008, 2013, 2018),
 '27-4014': (2003, 2013),
 '27-4021': (2003, 2008, 2013, 2018),
 '27-4031': (2003, 2008, 2018),
 '27-4032': (2003, 2008, 2013, 2018),
 '27-4099': (2008, 2013),
 '29-0000': (2003, 2008, 2013, 2018),
 '29-1011': (2003, 2008, 2013, 2018),
 '29-1020': (2003,),
 '29-1021': (2008, 2013, 2018),
 '29-1031': (2003, 2008, 2013, 2018),
 '29-1041': (2003, 2008, 2013, 2018),
 '29-1051': (2003, 2008, 2013, 2018),
 '29-1061': (2003, 2008, 2013),
 '29-1062': (2003, 2008, 2013, 2018),
 '29-1063': (2003, 2008, 2013, 2018),
 '29-1064': (2003, 2008, 2013),
 '29-1065': (2003, 2008, 2013, 2018),
 '29-1066': (2003, 2008, 2013, 2018),
 '29-1067': (2003, 2008, 2013, 2018),
 '29-1069': (2008, 2013, 2018),
 '29-1071': (2003, 2008, 2013, 2018),
 '29-1081': (2008, 2013, 2018),
 '29-1111': (2003, 2008),
 '29-1121': (2003, 2008),
 '29-1122': (2003, 2008, 2013, 2018),
 '29-1123': (2003, 2008, 2013, 2018),
 '29-1124': (2013, 2018),
 '29-1125': (2003, 2008, 2013, 2018),
 '29-1126': (2003, 2008, 2013, 2018),
 '29-1127': (2003, 2008, 2013, 2018),
 '29-1129': (2008, 2013, 2018),
 '29-1131': (2003, 2008, 2013, 2018),
 '29-1141': (2013, 2018),
 '29-1151': (2013,),
 '29-1161': (2013, 2018),
 '29-1171': (2013, 2018),
 '29-1181': (2018,),
 '29-1199': (2018,),
 '29-2010': (2018,),
 '29-2011': (2003, 2008, 2013),
 '29-2012': (2003, 2008, 2013),
 '29-2021': (2003, 2008, 2013, 2018),
 '29-2031': (2003, 2008, 2013, 2018),
 '29-2032': (2003, 2008, 2013, 2018),
 '29-2033': (2003, 2008, 2013, 2018),
 '29-2034': (2003, 2008, 2013, 2018),
 '29-2035': (2013, 2018),
 '29-2041': (2003, 2008, 2013, 2018),
 '29-2051': (2003, 2008, 2018),
 '29-2052': (2003, 2008, 2013, 2018),
 '29-2053': (2003, 2018),
 '29-2054': (2003, 2008),
 '29-2055': (2003, 2008, 2013, 2018),
 '29-2056': (2003, 2008, 2013, 2018),
 '29-2057': (2013, 2018),
 '29-2061': (2003, 2008, 2013, 2018),
 '29-2071': (2003, 2008, 2013, 2018),
 '29-2081': (2003, 2008, 2013, 2018),
 '29-2091': (2013, 2018),
 '29-2099': (2008, 2013, 2018),
 '29-9010': (2003,),
 '29-9011': (2008, 2013, 2018),
 '29-9012': (2008, 2013, 2018),
 '29-9091': (2003, 2008, 2013, 2018),
 '29-9099': (2008, 2013, 2018),
 '31-0000': (2003, 2008, 2013, 2018),
 '31-1011': (2003, 2008, 2013, 2018),
 '31-1012': (2003, 2008),
 '31-1013': (2008, 2013),
 '31-1014': (2013, 2018),
 '31-1015': (2018,),
 '31-2011': (2003, 2008, 2013, 2018),
 '31-2012': (2008,),
 '31-2021': (2003, 2008, 2013, 2018),
 '31-2022': (2003, 2008, 2013, 2018),
 '31-9011': (2003, 2008, 2013, 2018),
 '31-9091': (2003, 2008, 2013, 2018),
 '31-9092': (2003, 2008, 2013, 2018),
 '31-9093': (2003, 2008, 2013, 2018),
 '31-9094': (2003, 2008, 2013, 2018),
 '31-9095': (2003, 2008, 2013),
 '31-9096': (2003, 2008, 2013, 2018),
 '31-9097': (2013, 2018),
 '31-9099': (2008, 2013, 2018),
 '33-0000': (2003, 2008, 2013, 2018),
 '33-1011': (2013, 2018),
 '33-1012': (2003, 2008, 2013, 2018),
 '33-1021': (2008, 2013, 2018),
 '33-1099': (2008, 2013, 2018),
 '33-2011': (2003, 2008, 2013, 2018),
 '33-2021': (2008, 2013, 2018),
 '33-3011': (2013,),
 '33-3012': (2008, 2013, 2018),
 '33-3021': (2003, 2008, 2013, 2018),
 '33-3051': (2003, 2008, 2013, 2018),
 '33-9011': (2008, 2013, 2018),
 '33-9021': (2003, 2008, 2013, 2018),
 '33-9032': (2003, 2008, 2013, 2018),
 '33-9091': (2008, 2013, 2018),
 '33-9092': (2008, 2013, 2018),
 '33-9093': (2013, 2018),
 '33-9099': (2008, 2013, 2018),
 '35-0000': (2003, 2008, 2013, 2018),
 '35-1011': (2003, 2008, 2013, 2018),
 '35-1012': (2003, 2008, 2013, 2018),
 '35-2011': (2003, 2008, 2013, 2018),
 '35-2012': (2003, 2008, 2013, 2018),
 '35-2014': (2003, 2008, 2013, 2018),
 '35-2015': (2003, 2008, 2013, 2018),
 '35-2019': (2008, 2013),
 '35-2021': (2003, 2008, 2013, 2018),
 '35-3011': (2003, 2008, 2013, 2018),
 '35-3021': (2003, 2008, 2013, 2018),
 '35-3022': (2003, 2008, 2013, 2018),
 '35-3031': (2003, 2008, 2013, 2018),
 '35-3041': (2003, 2008, 2013, 2018),
 '35-9011': (2003, 2008, 2013, 2018),
 '35-9021': (2003, 2008, 2013, 2018),
 '35-9031': (2003, 2008, 2013, 2018),
 '35-9099': (2008, 2013, 2018),
 '37-0000': (2003, 2008, 2013, 2018),
 '37-1011': (2003, 2008, 2013, 2018),
 '37-1012': (2003, 2008, 2013, 2018),
 '37-2011': (2003, 2008, 2013, 2018),
 '37-2012': (2003, 2008, 2013, 2018),
 '37-2019': (2008,),
 '37-2021': (2003, 2008, 2013, 2018),
 '37-3011': (2003, 2008, 2013, 2018),
 '37-3013': (2003,),
 '37-3019': (2008,),
 '39-0000': (2003, 2008, 2013, 2018),
 '39-1011': (2008, 2013),
 '39-1021': (2003, 2008, 2013, 2018),
 '39-2011': (2003, 2008, 2013, 2018),
 '39-2021': (2003, 2008, 2013, 2018),
 '39-3021': (2003, 2008),
 '39-3031': (2003, 2008, 2013, 2018),
 '39-3091': (2003, 2008, 2013, 2018),
 '39-3092': (2018,),
 '39-3093': (2003, 2008),
 '39-3099': (2008,),
 '39-4021': (2003, 2008, 2013),
 '39-4031': (2013, 2018),
 '39-5011': (2003, 2018),
 '39-5012': (2003, 2008, 2013, 2018),
 '39-5092': (2003, 2008, 2013),
 '39-5094': (2008, 2013, 2018),
 '39-6011': (2003, 2008, 2013, 2018),
 '39-6012': (2003, 2013, 2018),
 '39-6021': (2008,),
 '39-7010': (2018,),
 '39-7011': (2013,),
 '39-9011': (2003, 2008, 2013, 2018),
 '39-9021': (2003, 2008, 2013, 2018),
 '39-9031': (2003, 2008, 2013, 2018),
 '39-9032': (2003, 2008, 2013, 2018),
 '39-9041': (2003, 2008, 2013, 2018),
 '39-9099': (2008, 2013, 2018),
 '41-0000': (2003, 2008, 2013, 2018),
 '41-1011': (2003, 2008, 2013, 2018),
 '41-1012': (2003, 2008, 2013, 2018),
 '41-2011': (2003, 2008, 2013, 2018),
 '41-2021': (2003, 2008, 2013, 2018),
 '41-2022': (2003, 2008, 2013, 2018),
 '41-2031': (2003, 2008, 2013, 2018),
 '41-3011': (2003, 2008, 2013, 2018),
 '41-3021': (2003, 2008, 2013, 2018),
 '41-3031': (2003, 2008, 2013, 2018),
 '41-3041': (2003, 2008, 2013, 2018),
 '41-3099': (2008, 2013, 2018),
 '41-4011': (2003, 2008, 2013, 2018),
 '41-4012': (2003, 2008, 2013, 2018),
 '41-9011': (2003, 2008, 2013, 2018),
 '41-9021': (2003, 2018),
 '41-9022': (2003, 2008, 2013, 2018),
 '41-9031': (2003, 2008, 2013, 2018),
 '41-9041': (2003, 2008, 2013, 2018),
 '41-9091': (2003, 2013),
 '41-9099': (2008, 2013, 2018),
 '43-0000': (2003, 2008, 2013, 2018),
 '43-1011': (2003, 2008, 2013, 2018),
 '43-2011': (2003, 2008, 2013, 2018),
 '43-3011': (2003, 2008, 2013, 2018),
 '43-3021': (2003, 2008, 2013, 2018),
 '43-3031': (2003, 2008, 2013, 2018),
 '43-3051': (2003, 2008, 2013, 2018),
 '43-3061': (2003, 2008, 2013, 2018),
 '43-3071': (2003, 2008, 2013, 2018),
 '43-3099': (2013, 2018),
 '43-4011': (2008, 2013, 2018),
 '43-4021': (2003, 2008, 2013),
 '43-4031': (2008, 2013, 2018),
 '43-4041': (2003, 2008, 2013, 2018),
 '43-4051': (2003, 2008, 2013, 2018),
 '43-4061': (2003, 2008, 2013, 2018),
 '43-4071': (2003, 2008, 2013, 2018),
 '43-4081': (2003, 2008, 2013, 2018),
 '43-4111': (2003, 2008, 2013, 2018),
 '43-4121': (2003, 2008, 2013, 2018),
 '43-4131': (2003, 2008, 2013, 2018),
 '43-4141': (2003, 2008, 2013, 2018),
 '43-4151': (2003, 2008, 2013),
 '43-4161': (2003, 2008, 2013, 2018),
 '43-4171': (2003, 2008, 2013, 2018),
 '43-4181': (2003, 2008, 2013, 2018),
 '43-4199': (2008, 2013, 2018),
 '43-5011': (2003, 2008, 2013, 2018),
 '43-5021': (2003, 2008, 2013, 2018),
 '43-5031': (2003, 2008, 2013, 2018),
 '43-5032': (2003, 2008, 2013, 2018),
 '43-5041': (2003, 2008, 2013, 2018),
 '43-5051': (2003, 2008, 2013, 2018),
 '43-5052': (2003, 2008, 2013, 2018),
 '43-5053': (2003, 2008, 2013, 2018),
 '43-5061': (2003, 2008, 2013, 2018),
 '43-5071': (2003, 2008, 2013, 2018),
 '43-5081': (2003, 2008, 2013, 2018),
 '43-5111': (2003, 2008, 2013, 2018),
 '43-6011': (2003, 2008, 2013, 2018),
 '43-6012': (2003, 2008, 2013, 2018),
 '43-6013': (2003, 2008, 2013, 2018),
 '43-6014': (2003, 2008, 2013, 2018),
 '43-9011': (2003, 2008, 2013, 2018),
 '43-9021': (2003, 2008, 2013, 2018),
 '43-9022': (2003, 2008, 2013, 2018),
 '43-9031': (2003, 2008, 2013),
 '43-9041': (2003, 2008, 2013, 2018),
 '43-9051': (2003, 2008, 2013, 2018),
 '43-9061': (2003, 2008, 2013, 2018),
 '43-9071': (2003, 2008, 2013, 2018),
 '43-9081': (2008, 2013, 2018),
 '43-9111': (2003, 2008, 2013, 2018),
 '43-9199': (2008, 2013, 2018),
 '45-0000': (2003, 2008, 2013, 2018),
 '45-1011': (2008, 2013, 2018),
 '45-2011': (2008, 2018),
 '45-2041': (2008, 2018),
 '45-2092': (2003, 2008, 2013, 2018),
 '45-2093': (2003, 2008, 2013, 2018),
 '45-4022': (2018,),
 '45-4023': (2018,),
 '47-0000': (2003, 2008, 2013, 2018),
 '47-1011': (2003, 2008, 2013, 2018),
 '47-2011': (2008, 2018),
 '47-2021': (2003, 2008, 2013, 2018),
 '47-2031': (2003, 2008, 2013, 2018),
 '47-2041': (2003, 2008, 2013, 2018),
 '47-2042': (2013,),
 '47-2043': (2008,),
 '47-2044': (2003, 2008, 2013, 2018),
 '47-2051': (2003, 2008, 2013, 2018),
 '47-2061': (2003, 2008, 2013, 2018),
 '47-2071': (2003, 2008, 2013, 2018),
 '47-2073': (2003, 2008, 2013, 2018),
 '47-2081': (2003, 2008, 2013, 2018),
 '47-2082': (2003, 2008, 2018),
 '47-2111': (2003, 2008, 2013, 2018),
 '47-2121': (2003, 2008, 2013, 2018),
 '47-2130': (2003,),
 '47-2131': (2008, 2013, 2018),
 '47-2132': (2013, 2018),
 '47-2141': (2003, 2008, 2013, 2018),
 '47-2151': (2003, 2008, 2013, 2018),
 '47-2152': (2003, 2008, 2013, 2018),
 '47-2161': (2003, 2008),
 '47-2171': (2003, 2008),
 '47-2181': (2003, 2008, 2013, 2018),
 '47-2211': (2003, 2008, 2013, 2018),
 '47-2221': (2003, 2008, 2013, 2018),
 '47-3011': (2003, 2008, 2013, 2018),
 '47-3012': (2003, 2008, 2013, 2018),
 '47-3013': (2003, 2008, 2013, 2018),
 '47-3014': (2018,),
 '47-3015': (2003, 2008, 2013, 2018),
 '47-3016': (2003, 2008, 2013, 2018),
 '47-3019': (2008, 2013, 2018),
 '47-4011': (2003, 2008, 2013, 2018),
 '47-4021': (2003, 2013, 2018),
 '47-4031': (2003, 2008, 2013),
 '47-4041': (2003, 2008, 2013, 2018),
 '47-4051': (2003, 2008, 2013, 2018),
 '47-4071': (2003, 2008, 2013, 2018),
 '47-4099': (2008, 2013),
 '47-5021': (2008, 2013, 2018),
 '47-5081': (2008, 2013),
 '49-0000': (2003, 2008, 2013, 2018),
 '49-1011': (2003, 2008, 2013, 2018),
 '49-2011': (2003, 2008, 2013, 2018),
 '49-2021': (2003, 2013),
 '49-2022': (2003, 2008, 2013, 2018),
 '49-2092': (2003, 2008, 2013),
 '49-2094': (2003, 2008, 2013, 2018),
 '49-2095': (2013,),
 '49-2096': (2003, 2008),
 '49-2097': (2003, 2008, 2013, 2018),
 '49-2098': (2003, 2008, 2013, 2018),
 '49-3011': (2003, 2008, 2013, 2018),
 '49-3021': (2003, 2008, 2013, 2018),
 '49-3022': (2003, 2008, 2013, 2018),
 '49-3023': (2003, 2008, 2013, 2018),
 '49-3031': (2003, 2008, 2013, 2018),
 '49-3041': (2003, 2008, 2013, 2018),
 '49-3042': (2003, 2008, 2013, 2018),
 '49-3043': (2018,),
 '49-3051': (2013, 2018),
 '49-3052': (2003, 2008, 2013, 2018),
 '49-3053': (2003, 2008, 2013, 2018),
 '49-3091': (2008,),
 '49-3092': (2003, 2008),
 '49-3093': (2003, 2008, 2013, 2018),
 '49-9011': (2018,),
 '49-9012': (2003, 2008, 2013, 2018),
 '49-9021': (2003, 2008, 2013, 2018),
 '49-9031': (2003, 2013, 2018),
 '49-9041': (2003, 2008, 2013, 2018),
 '49-9042': (2003, 2008),
 '49-9043': (2003, 2008, 2013, 2018),
 '49-9044': (2003, 2008, 2013, 2018),
 '49-9051': (2003, 2008, 2013, 2018),
 '49-9052': (2003, 2008, 2013, 2018),
 '49-9062': (2003, 2008, 2013, 2018),
 '49-9063': (2003, 2008, 2018),
 '49-9064': (2003,),
 '49-9069': (2008, 2013),
 '49-9071': (2013, 2018),
 '49-9091': (2003, 2008, 2013, 2018),
 '49-9094': (2003, 2008, 2013, 2018),
 '49-9095': (2003,),
 '49-9096': (2013, 2018),
 '49-9098': (2003, 2008, 2013, 2018),
 '49-9099': (2008, 2013, 2018),
 '51-0000': (2003, 2008, 2013, 2018),
 '51-1011': (2003, 2008, 2013, 2018),
 '51-2022': (2003, 2008, 2013),
 '51-2023': (2013,),
 '51-2028': (2018,),
 '51-2031': (2013,),

In [22]:
#for each year look at the number of times mentioned
gapdict={}
for y,x in occ_yeardict.items():
    a=pd.np.diff(x)
    if (5 not in a) and (len(a) != 0):
        a = a[0]
        gapdict.update({y:(a,x)})
gapdict

{'13-1011': (15, (2003, 2018)),
 '19-1012': (10, (2008, 2018)),
 '19-1029': (10, (2008, 2018)),
 '19-2021': (10, (2008, 2018)),
 '21-1029': (10, (2008, 2018)),
 '25-1054': (10, (2003, 2013)),
 '25-2032': (10, (2008, 2018)),
 '25-9021': (10, (2008, 2018)),
 '27-1013': (10, (2008, 2018)),
 '27-1014': (15, (2003, 2018)),
 '27-4014': (10, (2003, 2013)),
 '29-2053': (15, (2003, 2018)),
 '39-5011': (15, (2003, 2018)),
 '41-9021': (15, (2003, 2018)),
 '41-9091': (10, (2003, 2013)),
 '45-2011': (10, (2008, 2018)),
 '45-2041': (10, (2008, 2018)),
 '47-2011': (10, (2008, 2018)),
 '49-2021': (10, (2003, 2013)),
 '51-4012': (10, (2008, 2018)),
 '51-4051': (10, (2008, 2018)),
 '51-6051': (10, (2003, 2013)),
 '51-6062': (15, (2003, 2018)),
 '51-8012': (10, (2003, 2013)),
 '51-8013': (15, (2003, 2018)),
 '51-9071': (10, (2003, 2013)),
 '51-9082': (10, (2008, 2018)),
 '53-1011': (10, (2008, 2018)),
 '53-7121': (10, (2003, 2013))}

In [23]:
len(gapdict)

29

In [31]:
check= new_occupation["OCC_CODE"] == '13-1011'
new_occupation[check]

,OCC_CODE,OCC_TITLE,OCC_GROUP,TOT_EMP,EMP_PRSE,H_MEAN,A_MEAN,MEAN_PRSE,H_PCT10,H_PCT25,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,YEAR
33,13-1011,"Agents and Business Managers of Artists, Perfo...",detailed,30.0,46.2,26.210,54520.0,23.500,11.3000,14.1800,19.6400,38.7900,45.9400,23510.0,29490.0,40860.0,80670.0,95560.0,2018
1825,13-1011,"Agents and business managers of artists, perfo...",NaN,40.0,41.8,18.768,39032.0,20.808,12.5528,13.4232,14.8784,22.8072,28.9544,26112.0,27920.8,30940.0,47436.8,60234.4,2003

In [25]:
#new_occupation['YEAR'] = pd.to_datetime(new_occupation['YEAR'], format = "%Y")

In [26]:
new_occupation.to_sql("occ_table",sqlite3.connect('occ.db'), if_exists ="replace")

In [27]:
con = sqlite3.connect("occ.db")

In [28]:
occupation2 = pd.read_sql_query("SELECT * FROM occ_table WHERE YEAR=2003 AND OCC_CODE IN ('53-7061', '53-7062', '53-7063', '53-7064', '53-7081') ORDER BY OCC_CODE ASC", con)
occupation2

,index,OCC_CODE,OCC_TITLE,OCC_GROUP,TOT_EMP,EMP_PRSE,H_MEAN,A_MEAN,MEAN_PRSE,H_PCT10,H_PCT25,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,YEAR
0,2303,53-7061,Cleaners of vehicles and equipment,None,1290.0,14.05,13.5524,28179.2,8.500,8.0988,9.2888,11.5600,15.7284,21.9164,16843.6,19318.8,24051.6,32714.8,45580.4,2003
1,2304,53-7062,"Laborers and freight, stock, and material move...",None,12650.0,7.45,15.4836,32198.0,5.712,9.5472,11.3356,13.7496,17.1768,26.3568,19862.8,23575.6,28600.8,35734.0,54821.6,2003
2,2305,53-7063,Machine feeders and offbearers,None,1530.0,29.75,17.0816,35530.0,6.392,10.9140,12.8452,14.9124,20.4204,24.2964,22691.6,26717.2,31008.0,42466.0,50530.8,2003
3,2306,53-7064,"Packers and packagers, hand",None,4810.0,10.15,12.0700,25105.6,2.720,8.2144,9.3840,11.3424,14.0624,17.8976,17074.8,19522.8,23602.8,29246.8,37223.2,2003
4,2307,53-7081,Refuse and recyclable material collectors,None,410.0,29.45,15.9732,33218.0,7.480,10.6012,12.5596,15.2252,18.6456,22.3924,22052.4,26118.8,31660.8,38794.0,46566.4,2003